### ISSUE TITLE
Whitespace in Source column in values.csv

### ISSUE THREAD

**Issue by xrotwang** [davidainman/atlas-data#1]
While `cldf validate` does not complain (I'd say this is a bug), trying to create an SQLite database from the CLDF dataset fails, because of trailing whitespace after source keys in `values.csv`, e.g.
```
$ cldf createdb cldf-atlas/ atlas.sqlite
INSERT INTO `ValueTable_SourceTable` (`ValueTable_cldf_id`,`SourceTable_id`,`context`) VALUES (?,?,?)
(('agua1253_Gend-01', 'jakway1996aguaruna ', '68'),)
Traceback (most recent call last):
...
  File "/home/robert/venvs/atlas/lib/python3.12/site-packages/csvw/db.py", line 109, in insert
    db.executemany(sql, rows)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```
There seem to be 32 such cases, see
```
$ csvgrep -c Source cldf-atlas/values.csv -m " ["| wc -l
33
```

**Comment by davidainman** [comment]
Thanks for finding this; I'm not sure how I have been able to run the CLLD with this error.

**Comment by xrotwang** [comment]
> I'm not sure how I have been able to run the CLLD with this error.

It wasn't creation of the clld app db that failed. CLDF datasets can also be converted to SQLite databases (see https://github.com/cldf/cldf/blob/master/extensions/sql.md), and that's what didn't work here.
